# Generated by Django 4.2.1 on 2023-06-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exotico',
            old_name='edad',
            new_name='años',
        ),
        migrations.RenameField(
            model_name='exotico',
            old_name='raza',
            new_name='especie',
        ),
        migrations.RenameField(
            model_name='gato',
            old_name='edad',
            new_name='años',
        ),
        migrations.RenameField(
            model_name='perro',
            old_name='edad',
            new_name='años',
        ),
        migrations.AddField(
            model_name='exotico',
            name='nombre',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gato',
            name='nombre',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perro',
            name='nombre',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
