# Generated by Django 4.2.1 on 2023-06-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
