# Generated by Django 4.2.1 on 2023-06-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='exotico',
            name='teléfono',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gato',
            name='teléfono',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perro',
            name='teléfono',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
